# Generated by Django 5.0.1 on 2024-01-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoreward', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcorewardUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('coinstotales', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('is_staff', models.BooleanField()),
            ],
            options={
                'db_table': 'ecoreward_usuario',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
