# Generated by Django 5.0.1 on 2024-01-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoreward', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
