# Generated by Django 5.0.1 on 2024-01-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoreward', '0005_alter_usuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='passwd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
