# Generated by Django 5.0.1 on 2024-01-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoreward', '0007_rename_email_usuario_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='mail',
            new_name='email',
        ),
    ]
