/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package segonExamen;

import java.sql.Connection;
import java.sql.SQLException;
import segonExamen.controllers.ConnectionDB;
import segonExamen.controllers.ManageDBMetaData;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);

    System.out.println("Introduce el servidor");
    String server = scanner.nextLine();
    System.out.println("Introduce el puerto");
    int port = Integer.parseInt(scanner.nextLine());
    System.out.println("Introduce el nombre de usuario");
    String username = scanner.nextLine();
    System.out.println("Introduce la contraseña");
    String passwd = scanner.nextLine();

    System.out.println("Servidor: " + server);
    System.out.println("Puerto: " + port);
    System.out.println("Nombre de usuario: " + username);
    System.out.println("Contraseña: " + passwd);
           // Crear instancia de ConnectionDB
        ConnectionDB connectionDB = new ConnectionDB(server, port, username, passwd);

        // Conectar al DBMS
        Connection dbmsConnection = connectionDB.connectDBMS();

        if (dbmsConnection != null) {
            // Mostrar información del DBMS
            connectionDB.showInfo();

            // Crear instancia de ManageDBMetaData
            ManageDBMetaData manageDBMetaData = new ManageDBMetaData(server, port, username, passwd, "instituto");

            // Conectar a la base de datos
            Connection databaseConnection = manageDBMetaData.connectDatabase();

            if (databaseConnection != null) {
                // Mostrar información de las tablas (puedes ajustar el nombre de la tabla según tus necesidades)
                try {
                    System.out.println("Introduce el nombre de la tabla (o 'all' para todas las tablas):");
                    String tableName = scanner.nextLine();
                    manageDBMetaData.getTablesInfo(tableName);
                } catch (SQLException e) {
                    System.err.println("Error al obtener información de las tablas: " + e.getMessage());
                }
            } else {
                System.err.println("No se pudo conectar a la base de datos.");
            }
        } else {
            System.err.println("No se pudo conectar al DBMS.");
        }
    }
}

