# Generated by Django 5.0.1 on 2024-01-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoreward', '0004_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
