# Generated by Django 5.0.1 on 2024-01-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoreward', '0006_usuario_passwd_alter_usuario_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='mail',
        ),
    ]
