// default package
// Generated 26 nov 2023 19:40:10 by Hibernate Tools 5.2.13.Final
package enginerinversed.entities;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name = "Post", catalog = "kurigram")
public class Post implements java.io.Serializable {

	private int idPost;
	private User user;
	private Date createdAt;
	private String image;
	private Boolean isSubmitted;
	private Integer likes;
	private String text;
	private String title;

	public Post() {
	}

	public Post(int idPost) {
		this.idPost = idPost;
	}

	public Post(int idPost, User user, Date createdAt, String image, Boolean isSubmitted, Integer likes, String text,
			String title) {
		this.idPost = idPost;
		this.user = user;
		this.createdAt = createdAt;
		this.image = image;
		this.isSubmitted = isSubmitted;
		this.likes = likes;
		this.text = text;
		this.title = title;
	}

	@Id

	@Column(name = "idPost", unique = true, nullable = false)
	public int getIdPost() {
		return this.idPost;
	}

	public void setIdPost(int idPost) {
		this.idPost = idPost;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "isSubmitted")
	public Boolean getIsSubmitted() {
		return this.isSubmitted;
	}

	public void setIsSubmitted(Boolean isSubmitted) {
		this.isSubmitted = isSubmitted;
	}

	@Column(name = "likes")
	public Integer getLikes() {
		return this.likes;
	}

	public void setLikes(Integer likes) {
		this.likes = likes;
	}

	@Column(name = "text")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
