// default package
// Generated 26 nov 2023 19:40:10 by Hibernate Tools 5.2.13.Final
package enginerinversed.entities;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserFollowId generated by hbm2java
 */
@Embeddable
public class UserFollowId implements java.io.Serializable {

	private int userId;
	private long followId;

	public UserFollowId() {
	}

	public UserFollowId(int userId, long followId) {
		this.userId = userId;
		this.followId = followId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "follow_id", nullable = false)
	public long getFollowId() {
		return this.followId;
	}

	public void setFollowId(long followId) {
		this.followId = followId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserFollowId))
			return false;
		UserFollowId castOther = (UserFollowId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getFollowId() == castOther.getFollowId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + (int) this.getFollowId();
		return result;
	}

}
