/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ieseljust.exam;

import com.ieseljust.exam.controllers.JugadorController;
import com.ieseljust.exam.entities.*;
public class App {
        public static void main(String[] args) {
        JugadorController jugadorController = new JugadorController();

        // Perform operations using the JugadorController methods
        jugadorController.addJugador("Player1");
        jugadorController.addListofJugadors(5);
        jugadorController.updateJugador(1, "UpdatedPlayer");
    }
 }