/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package postgresql1a_raulsales;

import org.hibernate.Session;
import postgresql1a_raulsales.utils.HibernateUtil;

public class App {
    public static void main(String[] args) {
        Session session = null;
        try {
            session = HibernateUtil.getSessionFactory().openSession();
            if (session.isConnected()) {
                System.out.println("Conexión exitosa a la base de datos.");
            } else {
                System.out.println("No se pudo conectar a la base de datos.");
            }
        } catch (Exception e) {
            System.out.println("Error al intentar conectar a la base de datos: " + e.getMessage());
        } finally {
            if (session != null) {
                session.close();
            }
        }
    }
}
